### PR TITLE
Add method to display LCO on interrupt pin

### PR DESCRIPTION
**Pull request by merlinmb**
Added ability to toggle register to RPi_AS3935.py to ouput LCO frequency to IRQ (Interrupt) pin

### CODE REVIEW

**Comment by pcfens** [comment]
Thanks for the PR.
Before I merge it, could you try and add a get method and convert tabs to 4 spaces (so that things conform to pep8)? Let me know if you need any help.

**Comment by merlinmb** [comment]
will attempt replacing tabs with spaces.

**Comment by pcfens** [comment]
You shouldn't have to create a new PR if you don't want to - editing the existing commits and squashing should take care of it.

**Comment by merlinmb** [comment]
Yeah - I see its failing on the compile after a PR. 

Perhaps it's time I bought a guide to Git and refrained from PR's until I practice a bit.

**Comment by pcfens** [comment]
There's a free one that helped me a lot called [Pro Git](http://git-scm.com/book/en/v2).

In this case you probably want to rebase (I've done a little minor patching, getting ready to do some major test patching). then make your changes again. It's not too hard to do, just a matter of getting the right commands put together for your setup.

**Pull request closed without merging**
